### PR TITLE
Article tag should use property instead of name

### PR DESCRIPTION
**Pull request by teohm**
Changes:
- Article tag should use property instead of name

Was PR at https://github.com/kpumuk/meta-tags/pull/112

### CODE REVIEW

**Comment by teohm** [comment]
@Elektron1c97 We need this patch in production. 

BTW, in future, we might want to support all standard object properties specified by Facebook Open Graph [1]. What do you think?

[1] https://developers.facebook.com/docs/sharing/opengraph/object-properties

**Comment by Elektron1c97** [comment]
That's a very good idea!

I'll have a look at it when I'm back from my holidays next week.

**Comment by Elektron1c97** [comment]
Btw. released this in `1.1.1`

**Comment by teohm** [comment]
👍 😘

**Pull request merged**
